### PR TITLE
Changed filename convention to PascalCase

### PR DESCRIPTION
**Pull request by swarajpande5**
Renamed files using PascalCase #6  
(Edited the Branch)

### CODE REVIEW

**Review by chaudhary19 — APPROVED** [review]
Thank you I did not notice it earlier

**Review by chaudhary19 — CHANGES_REQUESTED** [review]
I have added and merged some files in my repo, can you please make changes to them too also for the convention as well. Then I will merge your changes into my repo.
Thank you

**Comment by swarajpande5** [comment]
Alright No Problem. :)

**Comment by swarajpande5** [comment]
Sorry, due to a repo error I had to close this one. I'll make another PR for the same.

**Comment by swarajpande5** [comment]
The new PR with the requested changes is #25

**Pull request closed without merging**
