### PR TITLE
Added Python template for fast I/O

### PR DESCRIPTION
**Pull request by Tejaswika**

### CODE REVIEW

**Review by aashutosh-agrawal — CHANGES_REQUESTED** [review]
It is ok but definitely can be made better.
Try to look at some good python coders' templates on codeforces. You'll get the idea.

**Comment by Tejaswika** [comment]
I have updated it, please have a look

**Review by aashutosh-agrawal — CHANGES_REQUESTED** [review]
There is almost the same template already in the repo. See [this](https://github.com/chaudhary19/Competitive-Algorithms-in-Cpp/blob/master/AW_Template.py)
Try to add something more and then we'll accept this one and close accepting PRs for this repo for the contest.

**Comment by chaudhary19** [comment]
Please look at the python templates of coders like "raj_1307" and "pajenegod" and kindly improve it

**Comment by Tejaswika** [comment]
This template is being referred from https://github.com/cheran-senthil/PyRival/blob/master/templates/template.py ,whose developer is "pajenegod", please check

**Review by chaudhary19 — APPROVED** [review]
Approved 💯

**Pull request merged**
