### PR TITLE
This modified template is inspired by Pulkit Chhabra's Template

### PR DESCRIPTION
**Pull request by Tejaswika**

### CODE REVIEW

**Review by chaudhary19 — CHANGES_REQUESTED** [review]
Please don't use that c_p_c(), instead of it write inside the main(), everything is fine, then I will merge it

**Comment by Tejaswika** [comment]
Removed c_p_c function

**Review by chaudhary19 — APPROVED** [review]

**Review by chaudhary19 — CHANGES_REQUESTED** [review]
please change the file name to something like A_Template_version1.cpp or else because I have merged another file into my repo due to which it is not possible for me to merge with the same name. I want to merge your code too In my repo

**Comment by Tejaswika** [comment]
I renamed it but then also the conflict is not solving

**Comment by Tejaswika** [comment]
Sir,now the conflict is solved

**Pull request merged**
