### PR TITLE
Added template for Python Competitive Coders

### PR DESCRIPTION
**Pull request by singhsuryanshu**
Added template for Python Competitive Coders
(Correct Branch)

### CODE REVIEW

**Review by chaudhary19 — CHANGES_REQUESTED** [review]
It's nice but you can improve it definitely. Kindly search "raj_1307" at codeforces and look at his python submissions, lookat his python template, I am not asking for whole stuff but you can take some stuff from his template

**Comment by singhsuryanshu** [comment]
> raj_1307

Sure

**Comment by singhsuryanshu** [comment]
Sure

**Comment by singhsuryanshu** [comment]
I have updated the template, please review..

**Comment by aashutosh-agrawal** [comment]
Well, Thank you for the changes.
Please fill the merged [PR form](https://docs.google.com/forms/d/e/1FAIpQLSexn0dft5QJtLvyGr7ME4-cmbYFCZW0jLNQ9bAIaQXF_YFoKQ/viewform) So that we may count this for the contest.

**Pull request merged**
